In [ ]:
#amaçlar :
#bagımlı ve bagımsız degiskenler arası iliskiyi tahmin etmek
#bagımlı degiskeni etkileyen bagımsız degiskenler ile bagımlı degiskeni tahmin etmek
#hangi bagımsız degiskenler bagımlı degiskeni daha cok etkiliyor

In [6]:
import pandas as pd
df=pd.read_csv("/content/Advertising.csv")

In [7]:
df=df.iloc[:,1:len(df)]
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [8]:
x = df.drop('sales',axis=1)
y = df[["sales"]]

In [9]:
x.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [10]:
y.head() #bagımlı degisken

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [11]:
#statsmodel ile model kurma
import statsmodels.api as sm

In [12]:
lm=sm.OLS(y,x)

In [13]:
model = lm.fit()

In [14]:
model.summary()
#rkare (R-squared) bagımsız degiskenlerin bagımlı degiskeni açıklama yüzdeki
#Prob (F-statistic): 0,05ten küçükse model anlamlı

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Wed, 20 Mar 2024   Prob (F-statistic):                   2.43e-171
Time:                        17:33:56   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [15]:
##scikit learn ile model kurma
from sklearn.linear_model import LinearRegression

In [16]:
lm=LinearRegression()

In [17]:
model = lm.fit(x,y)

In [18]:
model.intercept_

array([2.93888937])

In [19]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

Tahmin

Sales=2.94+TV*0.04+radio*0.19-newspaper*0.001

30 tv, 10 radio, 40 gazete

In [20]:
2.94+30*0.04+10*0.19-40*0.001

5.999999999999999

In [23]:
yeni_veri=[[30],[10],[40]]
yeni_veri=pd.DataFrame(yeni_veri).T
#T -> Transpoz

In [24]:
yeni_veri

0   1   2
0  30  10  40

In [25]:
model.predict(yeni_veri)
#predict -> tahmin et

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[6.15562918]])

In [26]:
from sklearn.metrics import mean_squared_error

In [27]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [28]:
model.predict(x)[0:10]

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [30]:
MSE = mean_squared_error(y,model.predict(x))
MSE

2.784126314510936

In [31]:
import numpy as np

In [32]:
RMSE = np.sqrt(MSE)
RMSE

1.6685701407225697

In [33]:
#sınama seti
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.20, random_state=99)

In [35]:
X_train.head()

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [37]:
y_train.head()

sales
16    12.5
51    10.7
97    15.5
164   11.9
71    12.4

In [38]:
X_test.head()

TV  radio  newspaper
135  48.3   47.0        8.5
127  80.2    0.0        9.2
191  75.5   10.8        6.0
66   31.5   24.6        2.2
119  19.4   16.0       22.3

In [39]:
y_test.head()

sales
135   11.6
127    8.8
191    9.9
66     9.5
119    6.6

In [41]:
lm = LinearRegression()
model = lm.fit(X_train,y_train)

In [46]:
np.sqrt(mean_squared_error(y_train, model.predict(X_train)))
#eğitim hatası
#egitim hatası varsa test hatası da vardir

1.7236824822650754

In [47]:
np.sqrt(mean_squared_error(y_test, model.predict(X_test)))

1.4312783138301641

In [ ]:
#k-katlı cv

In [49]:
from sklearn.model_selection import cross_val_score

In [50]:
cross_val_score(model, X_train,y_train,cv=10,scoring="neg_mean_squared_error")
#cv=10 yani 10 katlı, 10 farklı hata hesaplar

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [52]:
#cross validation(cv) MSE değeri
np.mean(-cross_val_score(model, X_train,y_train,cv=10,scoring="neg_mean_squared_error"))
#ortalama hata

3.3170289742341246

In [53]:
#RMSE
np.sqrt(np.mean(-cross_val_score(model, X_train,y_train,cv=10,scoring="neg_mean_squared_error")))

1.8212712522395242