#ElasticNet Regresyon
##Amaç hata kareler toplamını minimize etmek, katsayılara ceza uygular.
##L1 ve L2 birleşimi (Lasso, Ridge)

In [10]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.linear_model import RidgeCV, LassoCV, ElasticNetCV

In [7]:
df=pd.read_csv("/content/Hitters.csv")
df=df.dropna()
dms=pd.get_dummies(df[['Division','League','NewLeague']])
y=df["Salary"]
X_=df.drop(['Salary','League','Division','NewLeague'],axis=1).astype('float64')
X=pd.concat([X_, dms[['League_N','Division_W','NewLeague_N']]],axis=1)
X_train, X_test, y_train, y_test =train_test_split(X,
                                                   y,
                                                   test_size=0.25,
                                                   random_state=42)

In [11]:
enet_model=ElasticNet().fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.488e+06, tolerance: 3.899e+03
  model = cd_fast.enet_coordinate_descent(


In [12]:
 enet_model.coef_

array([ -1.86256172,   8.70489065,   5.10426375,  -2.89875799,
        -1.28642985,   5.24343682,   6.04480276,  -0.14701495,
        -0.21566628,  -0.7897201 ,   1.80813117,   0.80914508,
        -0.61262382,   0.26816203,   0.27172387,  -0.36530729,
        19.2186222 , -31.16586592,   8.98369938])

In [13]:
enet_model.intercept_

-6.465955602112331

In [15]:
enet_model.predict(X_train)[0:5]

array([325.74706292, 776.06632333, 522.86508419, 107.64091955,
       449.03139566])

In [16]:
enet_model.predict(X_test)[0:5]

array([ 577.79111731,  617.33202224, 1031.39113156,  364.95861575,
        489.51894393])

In [17]:
y_pred=enet_model.predict(X_test)

In [18]:
np.sqrt(mean_squared_error(y_test, y_pred))

357.1676548181246

In [19]:
r2_score(y_test, y_pred)

0.41070222469326867

##Model Tuning

In [20]:
enet_cv_model = ElasticNetCV(cv=10).fit(X_train, y_train)

In [21]:
enet_cv_model.alpha_

5230.7647364798695

In [22]:
enet_cv_model.coef_

array([ 0.62845434,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.        ,  0.        ,  0.09788752,  0.        ,
        0.27265769,  0.19270075,  0.00758665,  0.3106529 ,  0.        ,
       -0.        ,  0.        , -0.        ,  0.        ])

###final modeli

In [23]:
enet_tuned=ElasticNet(alpha=enet_cv_model.alpha_ ).fit(X_train, y_train)

In [25]:
y_pred=enet_cv_model.predict(X_test)

In [26]:
np.sqrt(mean_squared_error(y_test, y_pred))

394.15280563218795